databases:
  - name: realtime_search
    databaseName: realtime_search
    user: theophile
    plan: free

services:
  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker
    ripAllowList: # required - allow external connections from only these CIDR blocks
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home
    region: frankfurt # optional (defaults to oregon)
    plan: pro # optional (defaults to starter instance type)
    previewPlan: starter # optional (defaults to the value specified by 'plan')
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)
  # Redis 2 - all external connections allowed
  - type: redis
    name: lightning
    ipAllowList: # required - allow external connections from everywhere
      - source: 0.0.0.0/0
        description: everywhere
  # Redis 3 - no external connections allowed
  - type: redis
    name: private redis
    ipAllowList: [] # only allow internal connections
  - type: web
    name: realtime_search
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realtime_search
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default